[package]
name = "castle-game"
version = "0.1.11"
authors = ["Thomas Versteeg <thomasversteeg@gmx.com>"]
license = "GPL-3.0"
homepage = "https://github.com/tversteeg/castle-game"

readme = "README.md"
description = "2D destructible terrain strategy game"

repository = "https://github.com/tversteeg/castle-game.git"
keywords = ["game", "2d", "destructible"]
categories = ["games"]

build = "build.rs"

[badges]
travis-ci = {repository = "tversteeg/castle-game"}

[dependencies]
blit = "0.4"
direct-gui = "0.1"
minifb = "0.10"
specs = "0.10"
specs-derive = "0.1"
line_drawing = "0.6"

[build-dependencies]
blit = "0.4"
image = "0.18"
